apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: lab04-$STUDENT_NAME
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
  ports:
    - name: http
      port: 80
      targetPort: 80
